services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"

  user_service:
    build: ./user_service
    depends_on:
      - mongo

  order_service:
    build: ./order_service
    depends_on:
      - mongo
      - user_service

  api_gateway:
    build: ./Api_gateway
    ports:
      - "8080:8080"
    depends_on:
      - user_service
      - order_service